### ISSUE TITLE
Power switch 2 added as generic device

### ISSUE THREAD

**Issue by rindlerblabla** [kasteleman/de.ubisys#4]
Am still on v4.2 so maybe this is/will be fixed, but I am trying to add a power switch 2, but it ends up as a generic device. 
![Screenshot_20201001-203622_Homey](https://user-images.githubusercontent.com/28257974/94849905-64b84b80-0426-11eb-8b75-f01f22ced6be.jpg)

**Comment by kasteleman** [comment]
According to your screenshot you have a different Enhets-ID. Did you
recently buy this unit? Maybe a new firmware. This wil indeed be fixed
within the new Homey Firmware because the ID’s aren’t used anymore. Only
thing is, that I have to do some additional work to get both Relais
working. At this moment only the first is added.

Op do 1 okt. 2020 om 20:41 schreef rindlerblabla <notifications@github.com>

**Comment by rindlerblabla** [comment]
Okay, cool! Yes, it is new. Then I know. Good luck with getting the relay working with v5 then!
